# vim:ft=kitty

## name:     Archeotech Light (gruvbox)
## author:   Archeotech (theme-switch)
## blurb:    Light flavor for the gruvbox family — Sprint 25.

# The basic colors
foreground              #3c3836
background              #fbf1c7
selection_foreground    #fbf1c7
selection_background    #b57614

# Cursor colors
cursor                  #b57614
cursor_text_color       #fbf1c7

# URL underline color when hovering with mouse
url_color               #b57614

# Kitty window border colors
active_border_color     #b57614
inactive_border_color   #a89984
bell_border_color       #b57614

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #fbf1c7
active_tab_background   #b57614
inactive_tab_foreground #3c3836
inactive_tab_background #f2e5bc
tab_bar_background      #ebdbb2

# Colors for marks (marked text in the terminal)
mark1_foreground #fbf1c7
mark1_background #8f3f71
mark2_foreground #fbf1c7
mark2_background #b57614
mark3_foreground #fbf1c7
mark3_background #076678

# The 16 terminal colors

# black
color0 #504945
color8 #665c54

# red
color1 #9d0006
color9 #9d0006

# green
color2  #79740e
color10 #79740e

# yellow
color3  #b57614
color11 #af3a03

# blue
color4  #076678
color12 #076678

# magenta
color5  #8f3f71
color13 #b57614

# cyan
color6  #427b58
color14 #427b58

# white
color7  #bdae93
color15 #a89984
